-- CLIENTE

ALTER TABLE CLIENTE
    ADD COLUMN DataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- FUNCIONARIOS

ALTER TABLE FUNCIONARIOS
    ADD COLUMN Cargo VARCHAR(100);

-- ENTREGADORES

ALTER TABLE ENTREGADORES
    ADD COLUMN Disponivel BOOLEAN NOT NULL DEFAULT TRUE;

-- CATEGORIA

ALTER TABLE CATEGORIA
    ADD COLUMN Sustentavel BOOLEAN NOT NULL DEFAULT TRUE;

-- FORNECEDOR

ALTER TABLE FORNECEDOR
    ADD COLUMN CertificacaoAmbiental VARCHAR(150);

-- PRODUTOS

ALTER TABLE PRODUTOS
    ADD COLUMN Descricao VARCHAR(255);

-- PEDIDOS

ALTER TABLE PEDIDOS
    ADD COLUMN FormaPagamento VARCHAR(50);

-- PEDIDO_ITENS

ALTER TABLE PEDIDO_ITENS
    ADD COLUMN Desconto DECIMAL(10,2) NOT NULL DEFAULT 0.00;

-- ESTOQUE

ALTER TABLE ESTOQUE
    ADD COLUMN Observacao VARCHAR(255);