-- DONO

ALTER TABLE DONO
    ADD COLUMN DataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- PET

ALTER TABLE PET
    ADD COLUMN Sexo VARCHAR(10);

-- VETERINARIO

ALTER TABLE VETERINARIO
    ADD COLUMN Ativo BOOLEAN NOT NULL DEFAULT TRUE;

-- VACINA

ALTER TABLE VACINA
    ADD COLUMN Obrigatoria BOOLEAN NOT NULL DEFAULT FALSE;

-- ALERGIA

ALTER TABLE ALERGIA
    ADD COLUMN Cronica BOOLEAN NOT NULL DEFAULT FALSE;

-- CONSULTA

ALTER TABLE CONSULTA
    ADD COLUMN Status VARCHAR(20) NOT NULL DEFAULT 'AGENDADA';

-- INTERNAMENTO

ALTER TABLE INTERNAMENTO
    ADD COLUMN ObservacaoAlta VARCHAR(255);

-- FATURA

ALTER TABLE FATURA
    ADD COLUMN FormaPagamento VARCHAR(50);

-- PET_ALERGIA

ALTER TABLE PET_ALERGIA
    ADD COLUMN ReacaoObservada VARCHAR(255);

-- PET_VACINA

ALTER TABLE PET_VACINA
    ADD COLUMN LoteAplicado VARCHAR(50);

-- ITEM_FATURA

ALTER TABLE ITEM_FATURA
    ADD COLUMN Desconto DECIMAL(10,2) NOT NULL DEFAULT 0.00;
